### ISSUE TITLE
Simulation submodule

### ISSUE THREAD

**Issue by j-glow** [KNR-PW/selfie_carolocup#1]
Move gazebo_selfie_sim to organization on github, so it doesn't throw 404 error after redirect.

**Comment by pktiuk** [comment]
Faktycznie, trzeba przenieść

**Comment by pktiuk** [comment]
Naprawione. W naszej organizacji pojawiło się nowe repo: https://github.com/KNR-PW/gazebo_selfie_sim

**Comment by pktiuk** [comment]
Teraz możesz spróbować
